#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUSTEngine.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="STYX-PCG")]
	public partial class DatabaseLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPlayabilityTest(PlayabilityTest instance);
    partial void UpdatePlayabilityTest(PlayabilityTest instance);
    partial void DeletePlayabilityTest(PlayabilityTest instance);
    #endregion
		
		public DatabaseLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PlayabilityTest> PlayabilityTests
		{
			get
			{
				return this.GetTable<PlayabilityTest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PlayabilityTest")]
	public partial class PlayabilityTest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Pattern;
		
		private string _Playability;
		
		private int _PrologTime;
		
		private int _TotalTime;
		
		private double _ClosestFCDistance;
		
		private int _MaxDepthReached;
		
		private int _NodesExplored;
		
		private string _LevelString;
		
		private int _NrOfActions;
		
		private string _BestActions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPatternChanging(int value);
    partial void OnPatternChanged();
    partial void OnPlayabilityChanging(string value);
    partial void OnPlayabilityChanged();
    partial void OnPrologTimeChanging(int value);
    partial void OnPrologTimeChanged();
    partial void OnTotalTimeChanging(int value);
    partial void OnTotalTimeChanged();
    partial void OnClosestFCDistanceChanging(double value);
    partial void OnClosestFCDistanceChanged();
    partial void OnMaxDepthReachedChanging(int value);
    partial void OnMaxDepthReachedChanged();
    partial void OnNodesExploredChanging(int value);
    partial void OnNodesExploredChanged();
    partial void OnLevelStringChanging(string value);
    partial void OnLevelStringChanged();
    partial void OnNrOfActionsChanging(int value);
    partial void OnNrOfActionsChanged();
    partial void OnBestActionsChanging(string value);
    partial void OnBestActionsChanged();
    #endregion
		
		public PlayabilityTest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pattern", DbType="Int NOT NULL")]
		public int Pattern
		{
			get
			{
				return this._Pattern;
			}
			set
			{
				if ((this._Pattern != value))
				{
					this.OnPatternChanging(value);
					this.SendPropertyChanging();
					this._Pattern = value;
					this.SendPropertyChanged("Pattern");
					this.OnPatternChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Playability", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Playability
		{
			get
			{
				return this._Playability;
			}
			set
			{
				if ((this._Playability != value))
				{
					this.OnPlayabilityChanging(value);
					this.SendPropertyChanging();
					this._Playability = value;
					this.SendPropertyChanged("Playability");
					this.OnPlayabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrologTime", DbType="Int NOT NULL")]
		public int PrologTime
		{
			get
			{
				return this._PrologTime;
			}
			set
			{
				if ((this._PrologTime != value))
				{
					this.OnPrologTimeChanging(value);
					this.SendPropertyChanging();
					this._PrologTime = value;
					this.SendPropertyChanged("PrologTime");
					this.OnPrologTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTime", DbType="Int NOT NULL")]
		public int TotalTime
		{
			get
			{
				return this._TotalTime;
			}
			set
			{
				if ((this._TotalTime != value))
				{
					this.OnTotalTimeChanging(value);
					this.SendPropertyChanging();
					this._TotalTime = value;
					this.SendPropertyChanged("TotalTime");
					this.OnTotalTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosestFCDistance", DbType="Float NOT NULL")]
		public double ClosestFCDistance
		{
			get
			{
				return this._ClosestFCDistance;
			}
			set
			{
				if ((this._ClosestFCDistance != value))
				{
					this.OnClosestFCDistanceChanging(value);
					this.SendPropertyChanging();
					this._ClosestFCDistance = value;
					this.SendPropertyChanged("ClosestFCDistance");
					this.OnClosestFCDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDepthReached", DbType="Int NOT NULL")]
		public int MaxDepthReached
		{
			get
			{
				return this._MaxDepthReached;
			}
			set
			{
				if ((this._MaxDepthReached != value))
				{
					this.OnMaxDepthReachedChanging(value);
					this.SendPropertyChanging();
					this._MaxDepthReached = value;
					this.SendPropertyChanged("MaxDepthReached");
					this.OnMaxDepthReachedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodesExplored", DbType="Int NOT NULL")]
		public int NodesExplored
		{
			get
			{
				return this._NodesExplored;
			}
			set
			{
				if ((this._NodesExplored != value))
				{
					this.OnNodesExploredChanging(value);
					this.SendPropertyChanging();
					this._NodesExplored = value;
					this.SendPropertyChanged("NodesExplored");
					this.OnNodesExploredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelString", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LevelString
		{
			get
			{
				return this._LevelString;
			}
			set
			{
				if ((this._LevelString != value))
				{
					this.OnLevelStringChanging(value);
					this.SendPropertyChanging();
					this._LevelString = value;
					this.SendPropertyChanged("LevelString");
					this.OnLevelStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrOfActions", DbType="Int NOT NULL")]
		public int NrOfActions
		{
			get
			{
				return this._NrOfActions;
			}
			set
			{
				if ((this._NrOfActions != value))
				{
					this.OnNrOfActionsChanging(value);
					this.SendPropertyChanging();
					this._NrOfActions = value;
					this.SendPropertyChanged("NrOfActions");
					this.OnNrOfActionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestActions", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BestActions
		{
			get
			{
				return this._BestActions;
			}
			set
			{
				if ((this._BestActions != value))
				{
					this.OnBestActionsChanging(value);
					this.SendPropertyChanging();
					this._BestActions = value;
					this.SendPropertyChanged("BestActions");
					this.OnBestActionsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
